###
POST http://localhost:3443/api/player
Content-Type: application/json

{
    "name": "Monster",
    "gameId": "1"
}


###
GET http://localhost:3443/api/player/672b4c851d3e7a031591033a

###
DELETE http://localhost:3443/api/player/672b4d907d6f66c30af778df
